version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /path/to/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: K0c0matkhau
      POSTGRES_DB: StudentDB
